# Generated by Django 3.2.8 on 2021-10-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarehe', models.CharField(max_length=200)),
                ('jina', models.CharField(max_length=200)),
                ('maelezo', models.CharField(max_length=200)),
                ('muda', models.TimeField()),
                ('picha', models.ImageField(blank=True, upload_to='uploads/')),
            ],
        ),
    ]
